### ISSUE TITLE
Adding third todo item throws a TypeError.

### ISSUE THREAD

**Issue by MaxMommersteeg** [MaxMommersteeg/Qml.Net.TodoApp#1]
For some reason adding a third todo item results in  the following error:
>TypeError: Cannot read property 'title' of null

To reproduce:
1. Set `TodoApp.FrontEnd` as startup project
2. Delete `src/TodoApp.FrontEnd/todoApp.db` (if it exists, created on startup)
3. Run the application
4. Enter text in the textfield and click the `Submit` button

Not sure if this has anything to do with the current [Qml.Net](https://github.com/pauldotknopf/Qml.Net) list implementation or not.

I would be very grateful if you could give this a try once @pauldotknopf! :)

**Comment by pauldotknopf** [comment]
Will do. If I don't get to it this evening, def tomorrow.

**Comment by pauldotknopf** [comment]
So, I found the issue, but I'm kinda lost on how to fix it.

I think my approach of wrapping .NET lists/arrays via a fake V8 array is error prone.

I am currently working on a different approach. I hope to have it done by tomorrow. I will ping you when it's deployed/ready.

**Comment by MaxMommersteeg** [comment]
Fixed with pull request: https://github.com/MaxMommersteeg/Qml.Net.TodoApp/pull/2
